version: 0.2

env:
  shell: bash
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - pip3 install -r requirements.txt
      - pip3 install pytest 
      - python3 -m pytest tests/unit --junitxml=tests/unit/report.xml
artifacts:
  files:
    - '**/*'